In [1]:
import os
import pandas as pd
import shutil

Click below Link

[Click Here to Download the Hand Written Character Dataset](https://www.kaggle.com/datasets/vaibhao/handwritten-characters)

Extract the files

In [6]:
# Rename the Image

def rename_images(directory, new_name_prefix):
    # List all files in the directory
    files = os.listdir(directory)
    
    # Filter out only image files (assuming they have extensions like .jpg, .jpeg, .png)
    image_files = [f for f in files if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    # Loop over the image files and rename them
    for i, filename in enumerate(image_files):
        # Generate new name
        new_name = f"{new_name_prefix}_{i + 10000}.png"
        
        # Get full paths
        old_file = os.path.join(directory, filename)
        new_file = os.path.join(directory, new_name)
        
        # Rename the file
        os.rename(old_file, new_file)

In [4]:
train_path = r'Train'

for folder in os.listdir(train_path):
    directory = os.path.join(train_path, folder)
    new_name_prefix = folder
    rename_images(directory, new_name_prefix)

In [8]:
val_path = r'Validation'

for folder in os.listdir(val_path):
    directory = os.path.join(val_path, folder)
    new_name_prefix = folder 
    rename_images(directory, new_name_prefix)

In [9]:
train_data_ = {'Image_path':[], 'Label':[]}
train_path = r'Train'
for folder in os.listdir(train_path):
    image_path = os.path.join(train_path, folder)
    for img_path in os.listdir(image_path):
        train_data_['Image_path'].append(img_path)
        train_data_['Label'].append(folder)
train_annot = pd.DataFrame(train_data_)
train_annot

              Image_path     Label
0      airplane_1000.png  airplane
1      airplane_1001.png  airplane
2      airplane_1002.png  airplane
3      airplane_1003.png  airplane
4      airplane_1004.png  airplane
...                  ...       ...
49995     truck_5995.png     truck
49996     truck_5996.png     truck
49997     truck_5997.png     truck
49998     truck_5998.png     truck
49999     truck_5999.png     truck

[50000 rows x 2 columns]

In [10]:
val_data_ = {'Image_path':[], 'Label':[]}
val_path = r'Validation'

for folder in os.listdir(val_path):
    image_path = os.path.join(val_path, folder)
    for img_path in os.listdir(image_path):
        val_data_['Image_path'].append(img_path)
        val_data_['Label'].append(folder)
val_annot = pd.DataFrame(val_data_)
val_annot

              Image_path     Label
0     airplane_10000.png  airplane
1     airplane_10001.png  airplane
2     airplane_10002.png  airplane
3     airplane_10003.png  airplane
4     airplane_10004.png  airplane
...                  ...       ...
9995     truck_10995.png     truck
9996     truck_10996.png     truck
9997     truck_10997.png     truck
9998     truck_10998.png     truck
9999     truck_10999.png     truck

[10000 rows x 2 columns]

In [3]:
classes = train_annot.Label.unique()
classes

array(['#', '$', '&', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
       'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype=object)

In [4]:
class_map = {clss:id for id, clss in enumerate(classes)}
class_map

{'#': 0,
 '$': 1,
 '&': 2,
 '0': 3,
 '1': 4,
 '2': 5,
 '3': 6,
 '4': 7,
 '5': 8,
 '6': 9,
 '7': 10,
 '8': 11,
 '9': 12,
 '@': 13,
 'A': 14,
 'B': 15,
 'C': 16,
 'D': 17,
 'E': 18,
 'F': 19,
 'G': 20,
 'H': 21,
 'I': 22,
 'J': 23,
 'K': 24,
 'L': 25,
 'M': 26,
 'N': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38}

In [5]:
train_annot['Label'] = train_annot['Label'].map(class_map)
val_annot['Label'] = val_annot['Label'].map(class_map)

In [6]:
train_annot.head()

      Image_path  Label
0   ###_1000.png      0
1  ###_10000.png      0
2  ###_10001.png      0
3  ###_10002.png      0
4  ###_10003.png      0

In [7]:
train_annot.to_csv(r'annotations/hwr_train_annotations.csv', index = False)
val_annot.to_csv(r'annotations/hwr_test_annotations.csv', index = False)

In [8]:
train_annot = pd.read_csv(r'annotations/hwr_train_annotations.csv')
val_annot = pd.read_csv(r'annotations/hwr_test_annotations.csv')
train_annot.head()

      Image_path  Label
0   ###_1000.png      0
1  ###_10000.png      0
2  ###_10001.png      0
3  ###_10002.png      0
4  ###_10003.png      0

In [ ]:
train_path = r'Train'
path_ = r'Handwritten\Train'
i =0
for folder in os.listdir(train_path):
    image_path = os.path.join(train_path, folder)
    for img_path in os.listdir(image_path):
        src =os.path.join(image_path, img_path)
        dst= os.path.join(path_, img_path)
        shutil.copy(src, dst)

In [ ]:
test_path = r'Validation'
path_ = r'Handwritten\Test'
i =0
for folder in os.listdir(test_path):
    image_path = os.path.join(test_path, folder)
    for img_path in os.listdir(image_path):
        src =os.path.join(image_path, img_path)
        dst= os.path.join(path_, img_path)
        # print(src, dst)
        shutil.copy(src, dst)